const SCROLLBAR_WIDTH = 15
export const HEADER_WIDTH = 50
export const MEDIA_TABLET_MIN = 600
export const MEDIA_DESKTOP_MIN = 1000

export const MEDIA_QUERY_TABLET = MEDIA_TABLET_MIN + SCROLLBAR_WIDTH
export const MEDIA_QUERY_DESKTOP = MEDIA_DESKTOP_MIN + SCROLLBAR_WIDTH
