const SCROLLBAR_WIDTH = 15
export const HEADER_SMALL_WIDTH = 50
export const HEADER_LARGE_WIDTH = 70
export const MEDIA_TABLET_MIN = 700
export const MEDIA_DESKTOP_MIN = 1100

export const MEDIA_QUERY_TABLET = MEDIA_TABLET_MIN + SCROLLBAR_WIDTH
export const MEDIA_QUERY_DESKTOP = MEDIA_DESKTOP_MIN + SCROLLBAR_WIDTH
